[tools]
"aqua:cli/cli" = "2.83.0"
"aqua:go-task/task" = "3.45.4"
"aqua:GoogleContainerTools/container-structure-test" = "1.21.1"
"aqua:jqlang/jq" = "1.8.0"
"aqua:mikefarah/yq" = "4.48.1"

[hooks]
postinstall = [
  "mkdir -p {{config_root}}/.bin/goss",
  "gh release download --repo goss-org/goss --skip-existing --pattern *-linux-amd64 --output {{config_root}}/.bin/goss/goss",
  "gh release download --repo goss-org/goss --skip-existing --pattern dgoss --output {{config_root}}/.bin/goss/dgoss",
  "chmod +x {{config_root}}/.bin/goss/{goss,dgoss}",
]
